replicaCount: 1
image:
  repository: ghcr.io/qihuipan/internal-developer-platform
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  port: 8080
persistence:
  enabled: true
  size: 1Gi
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault
